/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://klmhllz2qra7bhhjmdzg7vkrni.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "OPENID_CONNECT",
    "aws_cognito_identity_pool_id": "us-east-2:9bcf01e4-f4bc-4758-9e6f-2ad4af578778",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_l5bWb7QCv",
    "aws_user_pools_web_client_id": "31b9so0tv5fc4vhugmljkj0gih",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
