builds:
  # - id: impervious-windows temporarily disabling arch that we dont currently support
  #   main: ./cmd/impd
  #   binary: impervious
  #   goos:
  #     - windows
  #   goarch:
  #     - 386
  #     - amd64
  - id: impervious-macos-amd64
    main: ./cmd/impd
    env:
      - CGO_ENABLED=1
    binary: impervious
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - gon gon-macos-amd64.json
  - id: impervious-macos-arm64
    main: ./cmd/impd
    env:
      - CGO_ENABLED=1
    binary: impervious
    goos:
      - darwin
    goarch:
      - arm64
    # hooks:
      # post:
        # - gon gon-macos-arm64.json
archives:
  - 
    format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_macosx_checksums.txt"
  algorithm: sha256

