builds:
  # - id: impervious-windows temporarily disabling arch that we dont currently support
  #   main: ./cmd/impd
  #   binary: impervious
  #   goos:
  #     - windows
  #   goarch:
  #     - 386
  #     - amd64
  - id: impervious-macos-amd64
    main: ./cmd/impd
    env:
      - CGO_ENABLED=1
    binary: impervious
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - 'codesign -f -s "Developer ID Application: Impervious Technologies Inc. (S722DY52YY)" -f --deep --options runtime dist/impervious-macos-amd64_darwin_amd64_v1/impervious'
        - zip dist/impervious-macos-amd64_darwin_amd64_v1/impervious.zip dist/impervious-macos-amd64_darwin_amd64_v1/impervious
  - id: impervious-macos-arm64
    main: ./cmd/impd
    env:
      - CGO_ENABLED=1
    binary: impervious
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - 'codesign -f -s "Developer ID Application: Impervious Technologies Inc. (S722DY52YY)" -f --deep --options runtime dist/impervious-macos-arm64_darwin_arm64/impervious'
        - zip dist/impervious-macos-arm64_darwin_arm64/impervious.zip dist/impervious-macos-arm64_darwin_arm64/impervious
archives:
  - 
    format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_macosx_checksums.txt"
  algorithm: sha256

