builds:
  - id: impervious-macos-arm64
    main: ./cmd/impd
    env:
      - CGO_ENABLED=1
    binary: impervious
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - gon gon-macos-arm64.json
archives:
  - 
    format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_macosx_arm_checksums.txt"
  algorithm: sha256
