builds:
  - id: impervious-windows
    main: ./cmd/impd
    binary: imp-daemon
    goos:
      - windows
    goarch:
      - 386
      - amd64
  - id: impervious-linux
    main: ./cmd/impd
    binary: imp-daemon
    goos:
      - linux
    goarch:
      - 386
      - amd64
      # - arm # linux arm seems to fail to compile, is it
      - arm64
      - s390x
  - id: impervious-macos-amd64
    main: ./cmd/impd
    binary: imp-daemon
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - gon gon-macos-amd64.json
  - id: impervious-macos-arm64
    main: ./cmd/impd
    binary: imp-daemon
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - gon gon-macos-arm64.json
#signs:
 #-
   #id: impervious-macos-amd64
   #cmd: gon
   #args:
   #- gon-macos-amd64.json
   #artifacts: all
 #-
   #id: impervious-macos-arm64
   #cmd: gon
   #args:
   #- gon-macos-arm64.json
   #artifacts: all

