builds:
  - id: impervious-windows
    main: ./cmd/impd
    binary: impervious
    goos:
      - windows
    goarch:
      - 386
      - amd64
  - id: impervious-linux
    main: ./cmd/impd
    binary: impervious
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - s390x
  - id: impervious-macos-amd64
    main: ./cmd/impd
    binary: impervious
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - gon gon-macos-amd64.json
  - id: impervious-macos-arm64
    main: ./cmd/impd
    binary: impervious
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - gon gon-macos-arm64.json