import type { NextPage } from "next";
import Head from "next/head";
// import ImpSearch from "../components/ImpSearch"; // TODO: implement
import Dashboard from "./d/dashboard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Impervious Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
      </Head>

      <main>
        <div className="m-w-full m-h-full h-screen">
          <Dashboard />
        </div>
      </main>
    </div>
  );
};

export default Home;
