// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imperviousai/imp-daemon/service/relay (interfaces: RelayService)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	comm "github.com/imperviousai/imp-daemon/comm"
)

// MockRelayService is a mock of RelayService interface.
type MockRelayService struct {
	ctrl     *gomock.Controller
	recorder *MockRelayServiceMockRecorder
}

// MockRelayServiceMockRecorder is the mock recorder for MockRelayService.
type MockRelayServiceMockRecorder struct {
	mock *MockRelayService
}

// NewMockRelayService creates a new mock instance.
func NewMockRelayService(ctrl *gomock.Controller) *MockRelayService {
	mock := &MockRelayService{ctrl: ctrl}
	mock.recorder = &MockRelayServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayService) EXPECT() *MockRelayServiceMockRecorder {
	return m.recorder
}

// Active mocks base method.
func (m *MockRelayService) Active() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Active")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Active indicates an expected call of Active.
func (mr *MockRelayServiceMockRecorder) Active() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Active", reflect.TypeOf((*MockRelayService)(nil).Active))
}

// HandleData mocks base method.
func (m *MockRelayService) HandleData(arg0 *comm.DIDCommMsg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleData indicates an expected call of HandleData.
func (mr *MockRelayServiceMockRecorder) HandleData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleData", reflect.TypeOf((*MockRelayService)(nil).HandleData), arg0)
}

// Shutdown mocks base method.
func (m *MockRelayService) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockRelayServiceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockRelayService)(nil).Shutdown))
}

// Type mocks base method.
func (m *MockRelayService) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRelayServiceMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRelayService)(nil).Type))
}
