// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imperviousai/imp-daemon/id (interfaces: Ion)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	did "github.com/hyperledger/aries-framework-go/pkg/doc/did"
	ion "github.com/imperviousai/imp-daemon/id/ion"
)

// MockIon is a mock of Ion interface.
type MockIon struct {
	ctrl     *gomock.Controller
	recorder *MockIonMockRecorder
}

// MockIonMockRecorder is the mock recorder for MockIon.
type MockIonMockRecorder struct {
	mock *MockIon
}

// NewMockIon creates a new mock instance.
func NewMockIon(ctrl *gomock.Controller) *MockIon {
	mock := &MockIon{ctrl: ctrl}
	mock.recorder = &MockIonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIon) EXPECT() *MockIonMockRecorder {
	return m.recorder
}

// CreateDid mocks base method.
func (m *MockIon) CreateDid(arg0 []ion.Service) (*did.Doc, uint32, []uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDid", arg0)
	ret0, _ := ret[0].(*did.Doc)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].([]uint32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateDid indicates an expected call of CreateDid.
func (mr *MockIonMockRecorder) CreateDid(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDid", reflect.TypeOf((*MockIon)(nil).CreateDid), arg0)
}

// ResolveDid mocks base method.
func (m *MockIon) ResolveDid(arg0 string) (*did.Doc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDid", arg0)
	ret0, _ := ret[0].(*did.Doc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDid indicates an expected call of ResolveDid.
func (mr *MockIonMockRecorder) ResolveDid(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDid", reflect.TypeOf((*MockIon)(nil).ResolveDid), arg0)
}

// UpdateDid mocks base method.
func (m *MockIon) UpdateDid(arg0 *did.Doc) (*did.Doc, uint32, []uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDid", arg0)
	ret0, _ := ret[0].(*did.Doc)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].([]uint32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// UpdateDid indicates an expected call of UpdateDid.
func (mr *MockIonMockRecorder) UpdateDid(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDid", reflect.TypeOf((*MockIon)(nil).UpdateDid), arg0)
}
