name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - staging
      - development
  pull_request:
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43.0
          args: --timeout=5m
        # env:
        #   GO111MODULES: off
